### PR TITLE
Resolve modules to their package.json directory (instead of their dirname)

### LINKED ISSUE #138: Build fails when the main field targets a sub-directory
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
Local package

**Describe the bug**
A clear and concise description of what the bug is (don't forget the logs if applicable).

My local package is not being transpiled when building an application with `yarn build`. This bug only happens when using `next-transpile-modules` version 5.

I have a monorepo built with `yarn workspaces` that contains two NextJS (v10) applications that share code between each other - a link to the repo is below. When running `yarn dev` each application is built and runs fine, but when running `yarn build` it fails because of webpack errors that indicate that the imported code is not being transpiled: `Module parse failed: Unexpected token (1:25)`
 
This only happens with `next-transpile-modules` version 5. If I downgrade to version 4.1.0 then the application builds fine.

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):

You can reproduce the issue using this repo + branch: https://github.com/cpv123/nextjs-sharing-code-monorepo/tree/next-transpile-modules-v5.

In the README I've added a small section 'Known issue with next-transpile-modules version 5' which describes the reproduction steps.

**Expected behavior**

`yarn build` should successfully build the application

**Setup**

- Next.js version: 10.0.3
- `next-transpile-modules` version: 5.0.0
- Node.js version: 14.15.0
- `npm`/`yarn` version: 1.21.1
- Operating System: MacOS
- Webpack 4 or 5: 4 (using default version from NextJS)

**Additional context**

* This is happening on both my local machine and in my CI/CD pipeline on Vercel.
* I have followed the upgrade steps for https://github.com/martpie/next-transpile-modules/releases/tag/5.0.0 i.e. adding a `main` field to each `package.json`. This allowed `yarn dev` to work.

### LINKED ISSUE #140: New resolution strategy breaks with @formatjs/intl-numberformat
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
I'm transpiling `@formatjs/intl-numberformat` with the new version 5 of `next-transpile-modules`. With version 4, I don't have any issues.

**Describe the bug**
I get the following build error:
```
Error: Can't resolve '@formatjs/intl-numberformat' in '/Users/valentin/test'
    at finishWithoutResolve (/Users/valentin/test/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
...
> Build error occurred
Error: next-transpile-modules: could not resolve module "@formatjs/intl-numberformat". Are you sure the name of the module you are trying to transpile is correct?
```

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):
- install `@formatjs/intl-numberformat`
- add it to the list of `withTM([])`

**Expected behavior**
The build should not failed and the module should be transpiled.

**Setup**

- Next.js version: 10.0.1
- `next-transpile-modules` version: 5.0.0
- Node.js version: 12.18.4
- `npm`/`yarn` version: 1.22.4
- Operating System: MacOS
- Webpack 4 or 5: 4

**Additional context**
I guess it's due to `@formatjs/intl-numberformat` "main" field being wrong: https://github.com/formatjs/formatjs/issues/2365

If yes, could we have a more explicit error message? Here it could have tell me that the package was found but the "main" field was not pointing to a valid file. What do you think?

### PR DESCRIPTION
**Pull request by martpie**
Fixes #138 
Fixes #140 

Still not sure if we want to go this way. But it matches the v4 behavior, and I've never heard any request for granular module transpilation in the same package. So I'd say it's quite safe

### CODE REVIEW

**Comment by alexandregme** [comment]
Nice! I think this is what I need

**Comment by martpie** [comment]
@alexandregme can you confirm that it solves the problems you're facing?

**Comment by cpv123** [comment]
@martpie I can confirm that this fixes #138. Thanks!

File: src/next-transpile-modules.js [hunk 1]
```diff
@@ -36,31 +40,47 @@ const regexEqual = (x, y) => {
...
+ * Return the root path (package.json directory) of a given module
+ * @param {string} module
+ */
+const getPackageRootDirectory = (module) => {
+  let packageDirectory;
+  let packageRootDirectory;
+
+  try {
+    // Get the module path
+    packageDirectory = resolve(CWD, module);
```
Comment (alizeait) [inline src/next-transpile-modules.js:53]: This will only look into the current working directory correct? What about when using yarn workspaces and some packages are hoisted outside the cwd? Seems to error out

Comment (martpie) [reply src/next-transpile-modules.js:53]: Answer line 63 ;)
