### PR TITLE
Exclude nested node_modules from transpilation

### LINKED ISSUE #151: Nested node_modules gets transpiled
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [ ] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ (you may not get support if you remove this line)

**Are you trying to transpile a local package or an npm package?**
local package

**Describe the bug**
When transpiling local package all of its node_modules get transpiled as well:
```js
withTranspileModules(['@top/utils', '@top/libs'], { debug: true });
```
log
```
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/isWeekend/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/isSunday/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/eachWeekendOfInterval/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/_lib/requiredArgs/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/endOfYear/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/startOfYear/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/addQuarters/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/_lib/requiredArgs/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/toDate/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/startOfQuarter/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/addWeeks/index.js
```

**To Reproduce**
Transpile any package

**Expected behavior**
Nested `node_modules` should be not be transpiled

**Setup**

- Next.js version: 10.0.3
- `next-transpile-modules` version: 6.0.0
- Node.js version: 14.15.0
- `yarn` version: 2.4.0
- Operating System: Mac Os
- Webpack: 4

### PR DESCRIPTION
**Pull request by ikibalnyi**
Resolves #151

### CODE REVIEW

File: src/next-transpile-modules.js [hunk 1]
```diff
@@ -120,12 +120,15 @@ const withTmInitializer = (modules = [], options = {}) => {
 
     // Generate Webpack condition for the passed modules
     // https://webpack.js.org/configuration/module/#ruleinclude
-    const match = (path) =>
-      modulesPaths.some((modulePath) => {
-        const transpiled = path.includes(modulePath);
+    const match = (path) => {
+      const lastEntry = path.split('/node_modules/').slice(-1)[0];
```
Comment (martpie) [inline src/next-transpile-modules.js:124]: This will be an issue on Windows which uses anti-slashes, can you handle this case as well?

**Review by martpie — CHANGES_REQUESTED** [review]

**Comment by martpie** [comment]
(otherwise it looks good and I'd be ready to merge this 👍

**Review by martpie — APPROVED** [review]
perfect, thank you very much

File: src/next-transpile-modules.js [hunk 2]
```diff
@@ -120,12 +120,15 @@ const withTmInitializer = (modules = [], options = {}) => {
 
     // Generate Webpack condition for the passed modules
     // https://webpack.js.org/configuration/module/#ruleinclude
-    const match = (path) =>
-      modulesPaths.some((modulePath) => {
-        const transpiled = path.includes(modulePath);
+    const match = (path) => {
+      const lastEntry = path.split(`${path.sep}node_modules${path.sep}`).slice(-1)[0];
+
+      return modules.some((modulePath) => {
```
Comment (alexandre-marchina) [inline src/next-transpile-modules.js:126]: Just a quick question, somewhat related with what i've commented here:
https://github.com/martpie/next-transpile-modules/issues/151#issuecomment-771957321

Shouldn't `modules.some`be `modulesPaths.some`? Was it intentional to compare the string with the package name instead of the resolved module path?
